swagger: '2.0'
info:
  title: cf-api
  description: API Gateway for Serverless function
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /counter:
    get:
      summary: Visitor Counter
      operationId: counter
      x-google-backend:
        address: https://australia-southeast1-elevated-cargo-355220.cloudfunctions.net/backend-serverless-function
        allowCors: True
      responses:
        200:
          description: Successful response
          schema:
            type: string
